# Generated by Django 4.2.6 on 2023-10-26 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correo', '0002_remove_registrocorreoform_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrocorreoform',
            old_name='usuarios',
            new_name='destinatarios',
        ),
    ]
